apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: serving-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: model-server
    spec:
      containers:
      - name: model-container
        image: tensorflow/serving
        ports:
        - containerPort: 8500
          name: grpc
        - containerPort: 8501
          name: rest
