apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: serving-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: model-server
    spec:
      containers:
      - name: model-container
        image: gcr.io/tfx-eric/serving
        command: ["bin/sh", "-c"]
        args:
          - mkdir "$MODEL_BASE_PATH/$MODEL_NAME";
            gsutil -m cp -r  "$MODEL_URI" "$MODEL_BASE_PATH/$MODEL_NAME";
            /usr/bin/tf_serving_entrypoint.sh;
        ports:
        - containerPort: 8500
          name: grpc
        - containerPort: 8501
          name: rest
