apiVersion: v1
kind: Service
metadata:
  labels:
    run: model-service
  name: model-service
spec:
  ports:
  - port: 8500
    targetPort: 8500
    name: grpc
  - port: 8501
    targetPort: 8501
    name: rest
  selector:
    app: model-server
  type: LoadBalancer
